// Generated by Wrangler on Mon Mar 18 2024 02:09:06 GMT+0200 (за східноєвропейським стандартним часом)
// by running `wrangler types`

interface Env {
  FIGEN_SERVER_ADDR: 'https://crate.monster';
}
